version: "3.3"

services:
  user-gateway-api:
    container_name: "user-gateway-api"
    build: ./
    volumes:
      - ./:/app
    ports:
      - 5001:5001
    ENV:
      - MONGO_URL=mongodb://mongo:27017/user-gateway-api